apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: wraymond
spec:
  type: NodePort
  selector:
    app: db-service
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432